### PR TITLE
Support more than two parameter's value 

### PR DESCRIPTION
**Pull request by koshishrijal**

### CODE REVIEW

**Comment by AashishBhetuwal** [comment]
Need multi-select parameter...just like this one
Been looking for this function for a long time.

**Comment by dilipshrest** [comment]
Need this functionality

**Comment by leojunio** [comment]
I need this functionality

**Comment by tagyoureit** [comment]
What functionality are you all asking for?  Not sure I understand.

**Comment by wxl3322335** [comment]
need checkbox parameter

**Comment by tagyoureit** [comment]
Did you all know that you can change the order of the values that show up in the parameter?  Just edit the parameter and drag/drop the items to rearrange them.  Your first two items will show up in this Extension's UI.  Making this Extension support multiple values requires a bit more work than just adding a simple for loop.  Thanks, Tag

**Pull request closed without merging**
